# 2020 Stack Flow Developer Survey Data Set

# ETL

####  Import Dependencies

In [5]:
import pandas as pd

####  Load the data set

In [15]:
#Load the data set 
filepath = "../Resources/2020StackOverFlow_DevSurvey/survey_results_public.csv"
data= pd.read_csv(filepath, index_col=0)
#df= pd.read_csv(filepath)
data.head(3)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN

In [16]:
#View Columns
data.columns

Index(['MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq', 'CompTotal',
       'ConvertedComp', 'Country', 'CurrencyDesc', 'CurrencySymbol',
       'DatabaseDesireNextYear', 'DatabaseWorkedWith', 'DevType', 'EdLevel',
       'Employment', 'Ethnicity', 'Gender', 'JobFactors', 'JobSat', 'JobSeek',
       'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

#### Drop uncessary columns

In [20]:
# Drop uncessary columns 
df = data.drop(
    ['CompFreq','CompTotal',
     'CurrencyDesc', 
     'CurrencySymbol',
     'DatabaseDesireNextYear',
     'LanguageDesireNextYear',
     'MiscTechDesireNextYear',
        'NEWDevOps', 'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck',
     'PlatformDesireNextYear',
     'PurchaseWhat',  
     'SOVisitFreq', 
     'SurveyEase', 
     'SurveyLength',
     'WebframeDesireNextYear',
     
       ], axis=1)#.dropna()
df.head(3)

,MainBranch,Hobbyist,Age,Age1stCode,ConvertedComp,Country,DatabaseWorkedWith,DevType,EdLevel,Employment,...,SOAccount,SOComm,SOPartFreq,Trans,UndergradMajor,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,NaN,Germany,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",...,No,"No, not at all",NaN,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,United Kingdom,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"Yes, definitely",Less than once per month or monthly,NaN,"Computer science, computer engineering, or sof...",NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,Russian Federation,NaN,NaN,NaN,NaN,...,Yes,"Yes, somewhat",A few times per month or weekly,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN

In [21]:
#View Column Names 
df.columns

Index(['MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'ConvertedComp',
       'Country', 'DatabaseWorkedWith', 'DevType', 'EdLevel', 'Employment',
       'Ethnicity', 'Gender', 'JobFactors', 'JobSat', 'JobSeek',
       'LanguageWorkedWith', 'MiscTechWorkedWith', 'OpSys', 'OrgSize',
       'PlatformWorkedWith', 'Sexuality', 'SOAccount', 'SOComm', 'SOPartFreq',
       'Trans', 'UndergradMajor', 'WebframeWorkedWith', 'WelcomeChange',
       'WorkWeekHrs', 'YearsCode', 'YearsCodePro'],
      dtype='object')

In [22]:
#Select only the data with the country United States & Drop Null Values 
us_df = df[(df['Country'] == 'United States')].dropna()
us_df.head(2)

,MainBranch,Hobbyist,Age,Age1stCode,ConvertedComp,Country,DatabaseWorkedWith,DevType,EdLevel,Employment,...,SOAccount,SOComm,SOPartFreq,Trans,UndergradMajor,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I am a developer by profession,Yes,36.0,12,116000.0,United States,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",Flask,Just as welcome now as I felt last year,39.0,17,13
14,I am a developer by profession,Yes,27.0,13,66000.0,United States,Firebase;Microsoft SQL Server,"Developer, desktop or enterprise applications;...","Associate degree (A.A., A.S., etc.)",Employed full-time,...,Yes,"Yes, definitely",A few times per week,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1

In [23]:
#Check for Null Values
for column in us_df.columns:
    print(f"Column {column} has {us_df[column].isnull().sum()} null values")

Column MainBranch has 0 null values
Column Hobbyist has 0 null values
Column Age has 0 null values
Column Age1stCode has 0 null values
Column ConvertedComp has 0 null values
Column Country has 0 null values
Column DatabaseWorkedWith has 0 null values
Column DevType has 0 null values
Column EdLevel has 0 null values
Column Employment has 0 null values
Column Ethnicity has 0 null values
Column Gender has 0 null values
Column JobFactors has 0 null values
Column JobSat has 0 null values
Column JobSeek has 0 null values
Column LanguageWorkedWith has 0 null values
Column MiscTechWorkedWith has 0 null values
Column OpSys has 0 null values
Column OrgSize has 0 null values
Column PlatformWorkedWith has 0 null values
Column Sexuality has 0 null values
Column SOAccount has 0 null values
Column SOComm has 0 null values
Column SOPartFreq has 0 null values
Column Trans has 0 null values
Column UndergradMajor has 0 null values
Column WebframeWorkedWith has 0 null values
Column WelcomeChange has 0 null values
Column WorkWeekHrs has 0 null values
Column YearsCode has 0 null values
Column YearsCodePro has 0 null values

In [24]:
# ### Select gender Column 
gender= us_df['Gender']
gender

Respondent
8          Man
14         Man
19         Man
42         Man
49         Man
         ...
62863      Man
62871      Man
62886      Man
62904      Man
62913    Woman
Name: Gender, Length: 2857, dtype: object

In [28]:
### Select gender equal to women Column 
women= us_df[(us_df ['Gender'] == 'Woman')]
women

,MainBranch,Hobbyist,Age,Age1stCode,ConvertedComp,Country,DatabaseWorkedWith,DevType,EdLevel,Employment,...,SOAccount,SOComm,SOPartFreq,Trans,UndergradMajor,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
128,I am a developer by profession,Yes,23.0,14,80000.0,United States,Microsoft SQL Server;MySQL,"Developer, back-end;Developer, desktop or ente...",Some college/university study without earning ...,Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",Angular.js;ASP.NET Core;React.js,Just as welcome now as I felt last year,37.0,5,4
139,I am a developer by profession,No,30.0,17,45000.0,United States,Microsoft SQL Server;MongoDB;MySQL,"Database administrator;Designer;Developer, bac...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",A few times per month or weekly,Yes,"Computer science, computer engineering, or sof...",Angular,Just as welcome now as I felt last year,40.0,13,8
252,I am a developer by profession,Yes,27.0,12,122780.0,United States,MySQL;PostgreSQL,"Developer, front-end;Developer, full-stack;Dev...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"Yes, definitely",A few times per month or weekly,No,"Information systems, information technology, o...",Angular;Angular.js;jQuery,Just as welcome now as I felt last year,41.0,15,6
326,I am a developer by profession,Yes,21.0,11,24000.0,United States,MongoDB,"Developer, front-end;Developer, full-stack;Dev...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed part-time,...,Yes,Neutral,Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",Angular;Express;React.js,Somewhat more welcome now than last year,25.0,4,3
466,I am a developer by profession,Yes,25.0,10,68000.0,United States,Cassandra;Couchbase;MongoDB;SQLite,"Designer;Developer, embedded applications or d...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,...,Yes,"Yes, definitely",A few times per month or weekly,Yes,"Computer science, computer engineering, or sof...",Angular.js;Express;React.js,Just as welcome now as I felt last year,40.0,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61594,I am a developer by profession,No,59.0,16,85000.0,United States,Microsoft SQL Server,"Developer, back-end;Developer, front-end","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"Yes, somewhat",Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,30,25
62044,I am a developer by profession,Yes,56.0,15,250000.0,United States,Microsoft SQL Server;MySQL;SQLite,Data or business analyst;Data scientist or mac...,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",...,Yes,"Yes, definitely",Less than once per month or monthly,Yes,"Another engineering discipline (such as civil,...",ASP.NET;jQuery,Just as welcome now as I felt last year,50.0,41,38
62715,I am a developer by profession,No,60.0,25,95000.0,United States,Elasticsearch;Microsoft SQL Server;MongoDB;Pos...,"Designer;Developer, back-end;Developer, deskto...","Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",...,Yes,"No, not really",I have never participated in Q&A on Stack Over...,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Drupal;jQuery;Vue.js,Just as welcome now as I felt last year,25.0,30,27
62803,I am a developer by profession,Yes,44.0,9,106000.0,United States,DynamoDB;Elasticsearch;Firebase;MariaDB;Micros...,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,Neutral,Less than once per month or monthly,Yes,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET Core;Flask,Just as welcome now as I felt last year,50.0,35,25
62913,"I am not primarily a developer, but I write co...",No,33.0,33,55000.0,United States,Firebase;Microsoft SQL Server;MySQL;PostgreSQL,"Engineer, site reliability","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",I have never participated in Q&A on Stack Over...,No,"A humanities discipline (such as literature, h...",ASP.NET Core;Express;jQuery;React.js,Not applicable - I did not use Stack Overflow ...,40.0,Less than 1 year,Less than 1 year

In [27]:
# Select only the data with the gender equal to "Man"
men= us_df[(us_df ['Gender'] == 'Man')]
men

,MainBranch,Hobbyist,Age,Age1stCode,ConvertedComp,Country,DatabaseWorkedWith,DevType,EdLevel,Employment,...,SOAccount,SOComm,SOPartFreq,Trans,UndergradMajor,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I am a developer by profession,Yes,36.0,12,116000.0,United States,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",Flask,Just as welcome now as I felt last year,39.0,17,13
14,I am a developer by profession,Yes,27.0,13,66000.0,United States,Firebase;Microsoft SQL Server,"Developer, desktop or enterprise applications;...","Associate degree (A.A., A.S., etc.)",Employed full-time,...,Yes,"Yes, definitely",A few times per week,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
19,I am a developer by profession,No,24.0,15,83400.0,United States,MariaDB;Microsoft SQL Server,"Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,Neutral,Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
42,I am a developer by profession,No,32.0,14,130000.0,United States,Microsoft SQL Server;MySQL;Oracle;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
49,I am a developer by profession,No,23.0,15,52000.0,United States,Microsoft SQL Server,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,Neutral,Less than once per month or monthly,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62860,I am a developer by profession,Yes,52.0,11,280000.0,United States,Microsoft SQL Server,"Designer;Developer, back-end;Developer, deskto...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"Yes, somewhat",Less than once per month or monthly,No,"A business discipline (such as accounting, fin...",ASP.NET;jQuery,Just as welcome now as I felt last year,58.0,40,36
62863,I am a developer by profession,Yes,30.0,11,230000.0,United States,MongoDB;PostgreSQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Information systems, information technology, o...",Express;React.js,Just as welcome now as I felt last year,40.0,10,7
62871,I am a developer by profession,Yes,34.0,16,150000.0,United States,PostgreSQL,"Developer, back-end;Developer, desktop or ente...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,...,Yes,"Yes, somewhat",Less than once per month or monthly,No,"A business discipline (such as accounting, fin...",React.js,Just as welcome now as I felt last year,40.0,7,4
62886,I am a developer by profession,Yes,32.0,24,102700.0,United States,Microsoft SQL Server;Redis,"Developer, back-end;Developer, front-end;Devel...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,...,Yes,"No, not really",Less than once per month or monthly,No,"Information systems, information technology, o...",Angular;Angular.js;ASP.NET Core,Somewhat more welcome now than last year,45.0,7,5
62904,I am a developer by profession,Yes,33.0,24,95000.0,United States,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,"Developer, back-end;Developer, desktop or ente...","Associate degree (A.A., A.S., etc.)",Employed full-time,...,Yes,"Yes, definitely",A few times per month or weekly,No,"Computer science, computer engineering, or sof...",Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,50.0,9,7

In [ ]:
# Save New cleaned File 
output_file_path = "../Resources/2020StackOverFlow_DevSurvey/clean_survey_results_public.csv""]
us_df.to_csv(output_file_path, index=False)